# Generated by Django 4.0 on 2023-09-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='ecommerce_app.ProductCart', to='ecommerce_app.Product'),
        ),
    ]
