name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Current Branch
        run: git branch --show-current

      - name: Checkout Dockers
        run: docker compose up -d 
